Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
Style/AccessorMethodName:
  Enabled: false
Style/VariableName:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false

AllCops:
  Exclude:
    - 'db/**/*'
